language: node_js
node_js:
  - "0.10"
services:
  - postgresql
addons:
  postgresql: "9.3"
  sauce_connect: true
notifications:
  email: false
script:
  - npm run syntax
  - npm test
before_script:
  - psql -c 'create database evernode_test;' -U postgres
  - cd test/scripts; ./create-db.sh evernode_test; cd ../..;
  - PORT=5555 node server/index.js&
  - sleep 5
after_script:
  - npm run coveralls
  - npm run e2e
env:
  global:
    - DATABASE_URL=postgres://postgres@localhost/evernode_test
    - AWS_BUCKET=sj-evernode-test
    # AWS_SECRET_ACCESS_KEY
    - secure: agxGf+JMBVb+ogxB6F5RpXrkZ60Wz6zPR1xuuKWvxoXn4G0mhXD/cBdQQ9wMQqrct+PryAAJPMgIn+JBgFxTUDw+2+35XztnYwObj59YaILlOQLTye6GvaN6cAM0lS/JFUD+UpSwl1xqvq96ebmbmuUOAkU/JgFCTJ93xy4u4Gs=
    # AWS_ACCESS_KEY_ID
    - secure: CNyc/MeyU+NlJWl//btM9lMSXx2RcecWRA1ssDB7EMu+MHQAtfULvPNFN7mff0mGp6JglhCOUGB+8JpXj8p10K2BulmZnXKDBwnfiN1EqJekaNBc7UTBfFQhQcKsj0l9l1ToQw08r46Fc8C8qanhsoYvh81B1JFx3auSGG8qpa8=
    # SAUCE_ACCESS_KEY
    - secure: eKvajzdciARHy0DOL/W9zs/6dEIr8BQFNgOFXOTN3lq/MNXfFtu75dlDEZTMJc2seqSWWOmLV3OQAAKYWIQIdQr4nbfnwPHAWQECofWSTCtWVLq/XXKhk9sxHsd0ECGu/zZvf7L8exuwwfS+p0UrCePULPQHSXKiIw4rdEzUflc=
    # SAUCE_USERNAME
    - secure: e+IDFdxhhBoruh6wPHE0jksIZdTpN5spjscM1/twXcH9WsL12Npe07LUhM9L2YCYBbQ8DXwrwizJJV5VYwLm8aWn94QxV9kHaLeXq6j749TXtTLh7T+K3SlKm8oDRsHBFSFZ0QU7jGUs+XrAxgtoJoNxrklJQBmaPtLioY+zAvg=
